const fs = require('fs');
const os = require('os');
const path = require('path');

const {
  DEFAULT_VOICE_ID,
  buildGenerationPlan,
  fileNameForCardId,
  main,
  parseArgs,
  renderManifest,
  requireApiKey,
} = require('../../scripts/generate-elevenlabs-audio');

describe('generate-elevenlabs-audio helpers', () => {
  it('uses the selected ElevenLabs voice as the default', () => {
    expect(DEFAULT_VOICE_ID).toBe('tTQzD8U9VSnJgfwC6HbY');
  });

  it('creates stable mp3 filenames from card ids', () => {
    expect(fileNameForCardId('0009')).toBe('0009.mp3');
    expect(fileNameForCardId('deck/card 1')).toBe('deck_card_1.mp3');
  });

  it('plans only missing files when force is false', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pronunciation-audio-'));
    fs.writeFileSync(path.join(tmp, '0009.mp3'), 'already generated');

    const plan = buildGenerationPlan(
      [
        { id: '0009', front: 'hola' },
        { id: '0010', front: 'buenos dias' },
      ],
      tmp,
      { force: false, limit: 0 },
    );

    expect(plan.toGenerate).toEqual([{ id: '0010', front: 'buenos dias', fileName: '0010.mp3' }]);
    expect(plan.skipped).toEqual([{ id: '0009', front: 'hola', fileName: '0009.mp3' }]);
  });

  it('respects the sample limit after skip filtering', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pronunciation-audio-'));

    const plan = buildGenerationPlan(
      [
        { id: '0009', front: 'hola' },
        { id: '0010', front: 'buenos dias' },
      ],
      tmp,
      { force: false, limit: 1 },
    );

    expect(plan.toGenerate).toEqual([{ id: '0009', front: 'hola', fileName: '0009.mp3' }]);
  });

  it('rejects invalid sample limits before planning a paid run', () => {
    expect(() => parseArgs(['--limit=abc'])).toThrow('--limit must be a non-negative integer');
    expect(() => parseArgs(['--limit='])).toThrow('--limit must be a non-negative integer');
    expect(() => parseArgs(['--limit=-1'])).toThrow('--limit must be a non-negative integer');
    expect(() => parseArgs(['--limit=1.5'])).toThrow('--limit must be a non-negative integer');
    expect(parseArgs(['--limit=0']).limit).toBe(0);
    expect(parseArgs(['--limit=5']).limit).toBe(5);
  });

  it('renders a static React Native manifest', () => {
    const manifest = renderManifest([
      { id: '0009', front: 'hola', fileName: '0009.mp3' },
      { id: '0010', front: 'buenos dias', fileName: '0010.mp3' },
    ]);

    expect(manifest).toContain('Generated by scripts/generate-elevenlabs-audio.js');
    expect(manifest).toContain('"0009": require(\'../../assets/audio/pronunciation/0009.mp3\')');
    expect(manifest).toContain('"0010": require(\'../../assets/audio/pronunciation/0010.mp3\')');
  });

  it('escapes card ids when rendering manifest keys', () => {
    const manifest = renderManifest([{ id: "deck/card '1'", front: 'hola' }]);

    expect(manifest).toContain(
      `"deck/card '1'": require('../../assets/audio/pronunciation/deck_card__1_.mp3')`,
    );
  });

  it('throws a clear error when the API key is missing', () => {
    expect(() => requireApiKey({})).toThrow('ELEVENLABS_API_KEY is required');
  });

  it('does not write files during a dry run', async () => {
    const writeSpy = jest.spyOn(fs, 'writeFileSync').mockImplementation(() => {});
    const logSpy = jest.spyOn(console, 'log').mockImplementation(() => {});

    try {
      await main(['--dry-run', '--limit=1'], {});
      expect(writeSpy).not.toHaveBeenCalled();
    } finally {
      writeSpy.mockRestore();
      logSpy.mockRestore();
    }
  });
});
