// Generated by scripts/generate-elevenlabs-audio.js.
// This empty manifest lets the app compile before pronunciation MP3s are generated.
export const pronunciationAudio: Record<string, number> = {};
