// Generated by scripts/generate-elevenlabs-audio.js.
// Re-run `npm run audio:generate` after adding or changing pronunciation audio.
export const pronunciationAudio: Record<string, number> = {
  '0001': require('../../assets/audio/pronunciation/0001.mp3'),
  '0002': require('../../assets/audio/pronunciation/0002.mp3'),
  '0003': require('../../assets/audio/pronunciation/0003.mp3'),
  '0004': require('../../assets/audio/pronunciation/0004.mp3'),
  '0005': require('../../assets/audio/pronunciation/0005.mp3'),
};
